
export const metadata = {
    title: "About",
    description: "Generated by Amr Waheed",
}


const page = () => {
    return (
        <div>
            About page
        </div>
    )
}

export default page