
export const metadata = {
    title: "Guest area",
    description: "Generated by Amr Waheed",
}


const page = () => {
    return (
        <div className="text-accent-600 font-bold text-4xl">
            welcome Amr
        </div>
    )
}

export default page