
export const metadata = {
    title: "Guest area",
    description: "Generated by Amr Waheed",
}


const page = () => {
    return (
        <div>
            Account page
        </div>
    )
}

export default page