import { auth } from "../_lib/auth"

export const metadata = {
    title: "Guest area",
    description: "Generated by Amr Waheed",
}

const page = async () => {
    const session = await auth()
    const firstName = session.user.name.split(' ').at(0)
    return (
        <div className="text-accent-600 font-bold text-4xl">
            welcome {firstName}
        </div>
    )
}

export default page