import Counter from "../_components/Counter"

export const metadata = {
    title: "Cabins",
    description: "Generated by Amr Waheed",
}

const page = async () => {
    return (
        <div>

        </div>
    )
}

export default page